##learning python with chai aur code

In [5]:
import numpy as np

arr_1D = np.array([1,2,3,4,5,6,])
print("1D array: ", arr_1D)

arr_2D = np.array([[1,2,3], [4,5,7]])
print("2D array: ", arr_2D)

1D array:  [1 2 3 4 5 6]
2D array:  [[1 2 3]
 [4 5 7]]


In [6]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_arr = np.array([1,2,3])
print("python array multiplication", np_arr*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


In [7]:
import time

start = time.time()
np_array = np.arange(1000000) *2
print("\n Numpy operation time", time.time()-start)


 Numpy operation time 0.010144472122192383


## array operation is faster than list operation

In [10]:
ones = np.ones((4,3))
print("\n array of ones \n", ones)

full = np.full((3,3), 7)
print("\n array of constant \n", full)

random = np.random.random((4,3))
print("\n array of random \n", full)

sequence = np.arange(0,10,2)
print("\n array of a sequence \n", sequence)




 array of ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 array of constant 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 array of random 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 array of a sequence 
 [0 2 4 6 8]


## Tensors and Vectors

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("\n Shape of array: ", arr.shape)
print("\n Dimension of array: ", arr.ndim)
print("\n Size of array: ", arr.size)
print("\n Data Type of array: ", arr.dtype)


 Shape of array:  (2, 3)

 Dimension of array:  2

 Size of array:  6

 Data Type of array:  int64


### array reshaping

In [13]:
arrayyy = np.arange(12)
print("Original Array: \n ", arrayyy)

reshaped = arrayyy.reshape((3,4))
print("Reshaped Array:\n ", reshaped)

flattened = reshaped.flatten()
print("Flattend Array: \n", flattened)

#ravel and flattened outputs same thing but ravel returns view not copy

transpose = reshaped.T
print("Transposed Array:\n ", transpose)


Original Array: 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## PHASE 2 
### numpy array operations

In [16]:
import numpy as np
ar = [1,2,3,4,5,6,7,8,9,0]

print("Basic Slicing", ar[2:7])
print("Stepwise Slicing", ar[2:8:2])
print("Negative Indexing ", ar[-3])

print("what we have for 2D is: ", arr)
print("Specific element", arr[1][2])
print("Entire Row", arr[1])
print("Entire Column", arr[:,1])


Basic Slicing [3, 4, 5, 6, 7]
Stepwise Slicing [3, 5, 7]
Negative Indexing  8
what we have for 2D is:  [[1 2 3]
 [4 5 6]]
Specific element 6
Entire Row [4 5 6]
Entire Column [2 5]


In [17]:
unsorted = np.array([3,4,34,42,3,232,54,45,45,4,54,323,23,23,2])
print("Sorted array --> ", np.sort(unsorted))

arr_2D_unsorted = np.array([[2,3],[3,4],[6,7]])
print("Sorted array by COLUMN --> ", np.sort(arr_2D_unsorted, axis=0))
print("Sorted array by Row --> ", np.sort(arr_2D_unsorted, axis=1))


Sorted array -->  [  2   3   3   4   4  23  23  34  42  45  45  54  54 232 323]
Sorted array by COLUMN -->  [[2 3]
 [3 4]
 [6 7]]
Sorted array by Row -->  [[2 3]
 [3 4]
 [6 7]]


## filtering 

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11])
even_nums = numbers[numbers%2==0] # NEW GOOD SHIT THIS IS
print("even shits are here --->", even_nums)

# FILTER WITH MASKKKKKK
mask = numbers>5
print("Numbers greater than 5 are", numbers[mask])

#INDEXING
where_result = np.where(numbers>5)
print("NP Where ---> ", numbers[where_result])


indices = [0,2,4]
print("Results ---> ",numbers[indices] )

condition_array = np.where(numbers>5, numbers*4, numbers)
print("Condition array, modifying the actual array", condition_array)

# works like if(condition) return numbers*4 else return numbers



even shits are here ---> [ 2  4  6  8 10]
Numbers greater than 5 are [ 6  7  8  9 10 11]
NP Where --->  [ 6  7  8  9 10 11]
Results --->  [1 3 5]
Condition array, modifying the actual array [ 1  2  3  4  5 24 28 32 36 40 44]


## adding and removing data

In [25]:
# combined shouldnt be like arr1+arr2
combined = np.concatenate((numbers, arrayyy))

print("Compataility ? ", numbers.shape == arrayyy.shape)
print(combined)


Compataility ?  False
[ 1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
original = np.array([[1,2],[3,4],
                     [5,6],[7,8]])

new_row = np.array([6,9])

with_new_row = np.vstack((original, new_row)) #use hstack for adding new column
print("here we have matrices with one extra row added to it \n", with_new_row)


# deleted = np.delete(arr, index)




here we have matrices with one extra row added to it 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]
 [6 9]]


In [ ]:
import matplotlib.pyplot as plt


In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("\n -------------------------Sales Data Analysis-------------------------")

print("shape of the data: ", sales_data.shape)
print("First 3 rows of the sales data:\n",sales_data[0:3])
print("First 3 column of the sales:\n",sales_data[0:, :3])

print("\n ------------------------TOTAL SALES PER YEAR--------------------------")

yearly_total = np.sum(sales_data[:, 1:], axis=0)
print("\nthe sum that comes here is sale in column wise\nyearly sales of all-----> ", yearly_total)

print("\n ------------------------MINIMUM SALES PER YEAR--------------------------")
min_sales = np.min(sales_data[:, 1:], axis=1)
print("\nthis gives min sales resturant wise \nminimum sales --------->", min_sales)

print("\n--------------------------------------------------------------------------")
print("MAX SALES PER YEAR THAT IS DO AXIS=0 i.e, COLUMN WISE")
print("--------------------------------------------------------------------------\n")


cumsum = np.cumsum(sales_data[:,1:], axis=1)
print("Cummulative sum is --------------->\n",cumsum)





 -------------------------Sales Data Analysis-------------------------
shape of the data:  (5, 5)
First 3 rows of the sales data:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
First 3 column of the sales:
 [[     1 150000 180000]
 [     2 120000 140000]
 [     3 200000 230000]
 [     4 180000 210000]
 [     5 160000 185000]]

 ------------------------TOTAL SALES PER YEAR--------------------------

the sum that comes here is sale in column wise
yearly sales of all----->  [ 810000  945000 1085000 1240000]

 ------------------------MINIMUM SALES PER YEAR--------------------------

this gives min sales resturant wise 
minimum sales ---------> [150000 120000 200000 180000 160000]

--------------------------------------------------------------------------
MAX SALES PER YEAR THAT IS DO AXIS=0 i.e, COLUMN WISE
--------------------------------------------------------------------------

Cummulative sum is ---------------> [[1